version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./Tesis_Back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A tesis_api worker -l info
    volumes:
      - ./Tesis_Back:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASENAME:-postgres}
      POSTGRES_USER: ${DATABASEUSER:-postgres}
      POSTGRES_PASSWORD: ${DATABASEPASSWORD:-postgres}
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
