# Generated by Django 5.2.5 on 2025-08-19 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('provincia', models.CharField(blank=True, max_length=80)),
                ('pais', models.CharField(default='Argentina', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RolParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100, unique=True)),
                ('caratula', models.CharField(max_length=250)),
                ('fuero', models.CharField(blank=True, max_length=100)),
                ('jurisdiccion', models.CharField(blank=True, max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='causa.causa')),
            ],
        ),
        migrations.CreateModel(
            name='EventoProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('plazo_limite', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='causa.causa')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('cuit_cuil', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='causa.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='CausaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_profesional', models.CharField(choices=[('patrocinante', 'Patrocinante'), ('apoderado', 'Apoderado'), ('colaborador', 'Colaborador')], max_length=20)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='causa.causa')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causa.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='CausaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='causa.causa')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causa.parte')),
                ('rol_parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='causa.rolparte')),
            ],
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['numero_expediente'], name='causa_causa_numero__991858_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='causaprofesional',
            unique_together={('causa', 'profesional', 'rol_profesional')},
        ),
        migrations.AlterUniqueTogether(
            name='causaparte',
            unique_together={('causa', 'parte', 'rol_parte')},
        ),
    ]
