# Generated by Django 5.2.5 on 2025-08-27 04:40

import causa.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='causa',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='causa',
            name='causa_causa_numero__991858_idx',
        ),
        migrations.AlterUniqueTogether(
            name='causaparte',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='causaprofesional',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='estado',
            field=models.CharField(blank=True, choices=[('abierta', 'Abierta'), ('en_tramite', 'En trámite'), ('con_sentencia', 'Con sentencia'), ('cerrada', 'Cerrada'), ('archivada', 'Archivada')], db_index=True, default='abierta', max_length=60),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fuero',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='causa',
            name='jurisdiccion',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='causa',
            name='numero_expediente',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='causaparte',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causa_partes', to='causa.causa'),
        ),
        migrations.AlterField(
            model_name='causaparte',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='causaparte',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_causas', to='causa.parte'),
        ),
        migrations.AlterField(
            model_name='causaprofesional',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas_profesionales', to='causa.causa'),
        ),
        migrations.AlterField(
            model_name='causaprofesional',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_causas', to='causa.profesional'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=causa.models.documento_upload_to),
        ),
        migrations.AlterField(
            model_name='eventoprocesal',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parte',
            name='cuit_cuil',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parte',
            name='documento',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='parte',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='parte',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['creado_en'], name='causa_causa_creado__ca0bae_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['actualizado_en'], name='causa_causa_actuali_9e706e_idx'),
        ),
        migrations.AddIndex(
            model_name='causaparte',
            index=models.Index(fields=['causa', 'rol_parte'], name='causa_causa_causa_i_706a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='causaprofesional',
            index=models.Index(fields=['causa', 'rol_profesional'], name='causa_causa_causa_i_3a6e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['causa', 'fecha'], name='causa_docum_causa_i_888a11_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['creado_en'], name='causa_docum_creado__5df70f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoprocesal',
            index=models.Index(fields=['fecha'], name='causa_event_fecha_e8a184_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoprocesal',
            index=models.Index(fields=['plazo_limite'], name='causa_event_plazo_l_e6f4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoprocesal',
            index=models.Index(fields=['causa', 'fecha'], name='causa_event_causa_i_eb7538_idx'),
        ),
        migrations.AddIndex(
            model_name='parte',
            index=models.Index(fields=['nombre_razon_social'], name='causa_parte_nombre__4365b8_idx'),
        ),
        migrations.AddIndex(
            model_name='parte',
            index=models.Index(fields=['documento'], name='causa_parte_documen_757fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='parte',
            index=models.Index(fields=['cuit_cuil'], name='causa_parte_cuit_cu_752657_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['apellido', 'nombre'], name='causa_profe_apellid_362cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['matricula'], name='causa_profe_matricu_608d09_idx'),
        ),
        migrations.AddConstraint(
            model_name='causa',
            constraint=models.UniqueConstraint(fields=('numero_expediente', 'fuero', 'jurisdiccion'), name='uniq_expediente_fuero_jurisdiccion'),
        ),
        migrations.AddConstraint(
            model_name='causaparte',
            constraint=models.UniqueConstraint(fields=('causa', 'parte', 'rol_parte'), name='uniq_causa_parte_rol'),
        ),
        migrations.AddConstraint(
            model_name='causaprofesional',
            constraint=models.UniqueConstraint(fields=('causa', 'profesional', 'rol_profesional'), name='uniq_causa_profesional_rol'),
        ),
        migrations.AddConstraint(
            model_name='eventoprocesal',
            constraint=models.CheckConstraint(condition=models.Q(('plazo_limite__isnull', True), ('plazo_limite__gte', models.F('fecha')), _connector='OR'), name='chk_plazo_no_anterior_a_fecha'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_eventos', to='causa.documento'),
        ),
        migrations.AddField(
            model_name='documentoevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_adjuntos', to='causa.eventoprocesal'),
        ),
        migrations.AddConstraint(
            model_name='documentoevento',
            constraint=models.UniqueConstraint(fields=('documento', 'evento'), name='uniq_doc_evento'),
        ),
    ]
