# Generated by Django 5.2.5 on 2025-09-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0002_documentoevento_alter_causa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
