# Generated by Django 5.2.5 on 2025-09-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0003_alter_domicilio_calle_alter_domicilio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaparte',
            name='rol_parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='causa.rolparte'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='cuit_cuil',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='documento',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='CausaGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('causa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grafo', to='causa.causa')),
            ],
        ),
    ]
