# Generated by Django 5.2.5 on 2025-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0005_alter_parte_cuit_cuil_alter_parte_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='cuit_cuil',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='parte',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
