# Generated by Django 5.2.5 on 2025-09-08 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0006_alter_parte_cuit_cuil_alter_parte_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaparte',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='causa.causa'),
        ),
    ]
