# Generated by Django 5.2.5 on 2025-09-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0007_alter_causaparte_causa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaprofesional',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='causa.causa'),
        ),
    ]
