# Generated by Django 5.2.5 on 2025-09-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0008_alter_causaprofesional_causa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causaparte',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_causas', to='causa.parte'),
        ),
    ]
