# Generated by Django 5.2.5 on 2025-10-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0009_alter_causaparte_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='domicilio',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
