# Generated by Django 5.2.5 on 2025-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0010_alter_parte_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte',
            name='cuit_cuil',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
