# Generated by Django 5.2.5 on 2025-10-10 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0012_alter_parte_cuit_cuil_alter_parte_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documento',
            name='causa_docum_causa_i_888a11_idx',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['causa'], name='causa_docum_causa_i_d62248_idx'),
        ),
    ]
