# Generated by Django 5.2.5 on 2025-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0013_remove_documento_causa_docum_causa_i_888a11_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='mime',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='documento',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
