# Generated by Django 5.2.5 on 2025-10-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0014_documento_mime_documento_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='causa',
            name='uniq_expediente_fuero_jurisdiccion',
        ),
    ]
