# Generated by Django 5.2.5 on 2025-09-09 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('db_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField()),
                ('citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(default='warning', max_length=16)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('raw_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('summary_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='ia.summaryrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
