# Generated by Django 5.2.5 on 2025-10-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causa', '0012_alter_parte_cuit_cuil_alter_parte_documento'),
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryrun',
            name='causa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_runs', to='causa.causa'),
        ),
    ]
