# Generated by Django 5.2.5 on 2025-10-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0003_summaryrun_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
