# Generated by Django 5.2.5 on 2025-10-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0004_alter_summaryrun_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryrun',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
