# Generated by Django 5.2.5 on 2025-10-12 21:09
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("ia", "0005_alter_summaryrun_options"),  # ajusta a tu última migración previa a la que falla
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;"),
    ]
