# Generated by Django 5.2.5 on 2025-10-12 21:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0006_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurisDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=128, unique=True)),
                ('titulo', models.TextField()),
                ('fuero', models.CharField(max_length=64)),
                ('jurisdiccion', models.CharField(max_length=128)),
                ('tribunal', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link_origen', models.TextField(blank=True, null=True)),
                ('s3_key_metadata', models.TextField(blank=True, null=True)),
                ('s3_key_document', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=64, null=True)),
                ('length_tokens', models.IntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JurisChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField()),
                ('span_start', models.IntegerField(blank=True, null=True)),
                ('span_end', models.IntegerField(blank=True, null=True)),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('doc', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ia.jurisdocument', to_field='doc_id')),
            ],
            options={
                'unique_together': {('doc', 'chunk_id')},
            },
        ),
    ]
