# Generated by Django 5.2.5 on 2025-10-12 23:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0007_jurisdocument_jurischunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurischunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
