# Generated by Django 5.2.5 on 2025-10-17 15:28

import django.db.models.deletion
import django.utils.timezone
import ia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0008_alter_jurischunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default=ia.models.gen_conv_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ia_conversation',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='ia.conversation')),
            ],
            options={
                'db_table': 'ia_idempotency_key',
                'unique_together': {('conversation', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(default=ia.models.gen_msg_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=16)),
                ('content', models.TextField()),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ia.conversation')),
            ],
            options={
                'db_table': 'ia_message',
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='ia_message_convers_94aa2d_idx')],
            },
        ),
    ]
