# Generated by Django 5.2.5 on 2025-10-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0010_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='openai',
            field=models.BooleanField(default=False),
        ),
    ]
