# Generated by Django 5.2.5 on 2025-10-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0011_conversation_openai'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
