# Generated by Django 5.2.5 on 2025-10-28 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0012_message_citations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='ia_conversa_user_id_2b8d3d_idx',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='openai',
            new_name='open_ai',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'updated_at'], name='ia_conversa_user_id_2dfe2b_idx'),
        ),
    ]
