# Generated by Django 5.2.5 on 2025-08-19 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiousuario',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
