# Generated by Django 5.2.5 on 2025-08-27 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_estudiousuario_fecha_alta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudiousuario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estudiojuridico',
            name='pagina_web',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='estudiojuridico',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-() ]*$', 'Formato de teléfono inválido')]),
        ),
        migrations.AddIndex(
            model_name='estudiojuridico',
            index=models.Index(fields=['nombre'], name='usuarios_es_nombre_c48a90_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiojuridico',
            index=models.Index(fields=['cuit'], name='usuarios_es_cuit_7ce1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiousuario',
            index=models.Index(fields=['estudio', 'vigente'], name='usuarios_es_estudio_61b1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiousuario',
            index=models.Index(fields=['usuario', 'vigente'], name='usuarios_es_usuario_23b65c_idx'),
        ),
        migrations.AddConstraint(
            model_name='estudiousuario',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('usuario', 'estudio'), name='uniq_usuario_estudio_vigente'),
        ),
    ]
